# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [6]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [9]:
A = np.arange(1, 16).reshape(3,5)

In [25]:
A, A.ndim, A.shape, A.size, A.dtype

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 2,
 (3, 5),
 15,
 dtype('int32'))

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [27]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [39]:
(B-C), (B*C), (B@C)

(array([[-1.,  0.,  1.],
        [ 2.,  3.,  4.],
        [ 5.,  6.,  7.]]),
 array([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]]),
 array([[12., 12., 12.],
        [30., 30., 30.],
        [48., 48., 48.]]))

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [41]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
np.exp(B), B.min(), B.min(axis=1)#row

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]]),
 1,
 array([1, 4, 7]))

In [57]:
B.min(axis=0) # Min val each col

array([1, 2, 3])

In [63]:
B.argmin() # Index min val whole matrix

0

In [61]:
B.argmin(axis=1) # Index for min in each row

array([0, 0, 0], dtype=int64)

In [73]:
B.sum(), B.mean(axis=0), np.median(B, axis=0)

(45, array([4., 5., 6.]), array([4., 5., 6.]))

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [75]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [81]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [83]:
It means that we are only interested in the row with that index. 

SyntaxError: invalid syntax (3243701423.py, line 1)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [85]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [87]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [90]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [92]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
Det är en tredimensionell matris, man vill ha axlar med 2 x 3 och sedan används -1 för att få den storleken på sista
dimensionen som passar. I det här fallet 5, vilket också är logiskt då 2 x 3 = 6, 5 x 6 = 30, vilket är antalet element i a.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [94]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [96]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [98]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [104]:
def add_mult_matrices(m1, m2, operation):
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("m1 or m2 not correct type")
    if operation == "add":
        if m1.shape != m2.shape:
            raise ValueError("m1 and m2 not same size")
        return (m1+m2)
    elif operation == "multiply":
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("Shape is not correct for multiplication")
        return (m1@m2)
    else:
        raise TypeError("operation neither 'add' or 'multiply'")
    

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [148]:
x = np.array([4,3])

In [150]:
#10.1.1 
#a)
x.ndim

1

In [152]:
#b 
5*x

array([20, 15])

In [154]:
#c
3*x

array([12,  9])

In [156]:
#d
5*x+3*x


array([32, 24])

In [158]:
#e
8*x

array([32, 24])

In [160]:
#f
4*x-x

array([12,  9])

In [166]:
#g
x_T = x.reshape(2, 1)

In [168]:
x_T.ndim

2

In [170]:
#h
result = add_mult_matrices(x, x_T, "add") # NEJ, INTE SAMMA SHAPE

ValueError: m1 and m2 not same size

In [174]:
result_i = np.linalg.norm(x)
result_i

5.0

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [190]:
A = np.array([[2, 1, -1],
              [1, -1, 1]])
B = np.array([[4, -2, 1],
              [2, -4, -2]])
C = np.array([[1, 2],
              [2, 1]])
D = np.array([[3, 4],
              [4, 3]])
D = np.array([[1],
              [2]])
I = np.array([[1, 0],
              [0, 1]])

In [192]:
#a 
2*A

array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [196]:
#b
B-2*A

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [198]:
#c
EJ DEFINIERAT DÅ INTE SAMMA SHAPE

In [200]:
#d
2*D-3*C

array([[-1, -4],
       [-2,  1]])

In [204]:
#e
D.T+2*D

array([[3, 4],
       [5, 6]])

In [206]:
#f
2*C.T-2*D.T

array([[ 0,  0],
       [ 2, -2]])

In [208]:
#g
A.T-B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [210]:
#h
result = add_mult_matrices(A, B, "multiply")

ValueError: Shape is not correct for multiplication

In [214]:
#i
result = add_mult_matrices(C, D, "multiply")
result

array([[5],
       [4]])

In [218]:
#j
result = add_mult_matrices(C, B, "multiply")
result

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [220]:
#k
result = add_mult_matrices(C, I, "multiply")
result

array([[1, 2],
       [2, 1]])

In [224]:
#l
result = add_mult_matrices(A, B.T, "multiply")
result

array([[5, 2],
       [7, 4]])

In [230]:
#10.2.2
A = np.array([[2, 3, 4],
              [5, 4, 1]])
result = add_mult_matrices(A, A.T, "multiply")
result

array([[29, 26],
       [26, 42]])

In [240]:
# 10.2.3
A = np.array([[1, 2], 
              [2, 4]])
B = np.array([[2, 1], 
              [1, 3]])
C = np.array([[4, 3], 
              [0, 2]])

AB = A@B  
AC = A@C  

print("AB:")
print(AB)
print("AC:")
print(AC)
print("Är AB lika med AC?\n", np.array_equal(AB, AC))

print("Är B lika med C?\n", np.array_equal(B, C))

AB:
[[ 4  7]
 [ 8 14]]
AC:
[[ 4  7]
 [ 8 14]]
Är AB lika med AC?
 True
Är B lika med C?
 False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [242]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [244]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [246]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [248]:
Anledningen till att sista värdet ändras är för att v2 är en view av v1. Alltså är det inte egen data utan den visar den 
faktiksa datan för v1. 

SyntaxError: invalid syntax (3986478532.py, line 1)